### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by ocramz** [michaelt/streaming-utils#5]
Sadly, lpaste.net has been taken over, so the example code does not work anymore.

**Comment by ocramz** [comment]
@chessai I saw you are currently maintaining this library? I am trying it out atm, can help with maintenance in the future if needed.

**Comment by chessai** [comment]
Awesome. This library has been moved to
https://github.com/haskell-streaming/streaming-utils. When I get to work
I'll add you.

**Comment by chessai** [comment]
you should have received an invite not too long ago

**Comment by chessai** [comment]
You may want to close this in favour of https://github.com/haskell-streaming/streaming-utils/issues/6

**Comment by ocramz** [comment]
Yep, thank you!
